# Generated by Django 4.2.3 on 2024-01-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
