# Generated by Django 4.2.3 on 2024-01-19 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0005_delete_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
