# Generated by Django 4.2.3 on 2024-01-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fashion_app', '0009_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
